# Generated by Django 4.2.6 on 2023-10-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuseraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuseraccount',
            name='last_name',
        ),
    ]
