# Generated by Django 4.2.6 on 2023-10-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_remove_customuseraccount_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuseraccount',
            old_name='dest_addr',
            new_name='dest_address',
        ),
        migrations.RenameField(
            model_name='customuseraccount',
            old_name='home_addr',
            new_name='home_address',
        ),
    ]
