# Generated by Django 4.2.6 on 2023-10-25 20:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customuser', '0003_rename_dest_addr_customuseraccount_dest_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserAccount',
            new_name='CustomUserAccountFields',
        ),
    ]
