# Generated by Django 4.2.6 on 2023-10-25 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customuser', '0004_rename_customuseraccount_customuseraccountfields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserAccountFields',
            new_name='CustomUserAccountField',
        ),
    ]
