# Generated by Django 4.2.6 on 2023-11-01 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customuser', '0005_rename_customuseraccountfields_customuseraccountfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuseraccountfield',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuseraccountfield',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
