version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py runserver
  post_build:
    commands:
      - curl http://127.0.0.1:5000
artifacts:
  files: imagedefinitions.json
  files: '**/*'