version: 0.2

phases:
  pre_build:
    commands:
      - docker --version
      - docker-compose --version
  build:
    commands:
      - docker-compose up --build -d dublintiffinservice
artifacts:
  files: imagedefinitions.json
  files: '**/*'