version: "3"
services:
  dublintiffinservice:
    build:
      context: .
    container_name: dublintiffinservice
    restart: always
    volumes:
      - ./dublintiffinservice:/dublintiffinservice
    ports:
      - 8000:8000
    networks:
      - dublintiffinservice
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
networks:
  dublintiffinservice:
