# Generated by Django 4.2.6 on 2023-11-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
